require "open-uri"

require_relative "../main.rb"

def fetch_game_info(title)
  begin
    bgg_data_for_title = HTTParty.get("http://boardgamegeek.com/xmlapi/search?search=#{title}&exact=1")

    if bgg_data_for_title["boardgames"] != nil && bgg_data_for_title["boardgames"]["boardgame"].is_a?(Hash)
      puts "Found one game for #{title}"

      id = bgg_data_for_title["boardgames"]["boardgame"]["objectid"]

      game_data = HTTParty.get("http://www.boardgamegeek.com/xmlapi/boardgame/#{id}")
      # binding.pry
      # game not on the site
      # multiple titles
      # missing column info
      # 
        @game = Game.new

        @game.title        = title
        @game.min_players  = game_data["boardgames"]["boardgame"]["minplayers"]
        @game.max_players  = game_data["boardgames"]["boardgame"]["maxplayers"]
        @game.min_playtime = game_data["boardgames"]["boardgame"]["minplaytime"]
        @game.max_playtime = game_data["boardgames"]["boardgame"]["maxplaytime"]
        @game.age_group    = game_data["boardgames"]["boardgame"]["age"]
        @game.description  = game_data["boardgames"]["boardgame"]["description"]
        @game.image        = game_data["boardgames"]["boardgame"]["image"]
        # @game.publisher    = game_data["boardgames"]["boardgame"]["boardgamepublisher"][0]["__content__"]
          # genre      = 
            
      @game.save
    else
      # binding.pry
      puts "ERROR"
      puts bgg_data_for_title["boardgames"]
    end
  rescue URI::InvalidURIError
    puts "Bad URL tried. Skipping... Tried #{title}"
  end
end

def fetch_titles_from_spielbound
  target = open("titles.txt", 'w')
  target.write("[")

  current_page = 1

  89.times do  
    doc = Nokogiri::HTML(open("http://spielbound.com/library?title=&field_playing_time_min__value=&&p=All&min=All&max=All&rating=All&sort_by=title&sort_order=ASC&page=#{current_page}"))

    doc.css("div.gamecard").each do |gamecard|
      target.write("\"")
      target.write(gamecard.css("h2.name a").text)
      target.write("\",")
      target.write("\n")
    end
    current_page += 1
  end

  target.write("]")
  target.close

  return nil
end

def populate_game_table
  x = ["7 Wonders: Duel",
    "7 Wonders: Leaders",
    "A Few Acres of Snow",
    "A Game of Thrones: The Board Game (Second Edition)",
    "A la carte",
    "A la carte: Dessert",
    "A Question of Scruples",
    "A Study in Emerald",
    "A Touch of Evil: The Supernatural Game",
    "Abagio",
    "Abalone",
    "Abandon Ship",
    "Abraca...what?",
    "Abyss",
    "Ace of Spies",
    "Acquire",
    "Across Words",
    "Adam & Eva",
    "Adventure Land",
    "Africana",
    "Age of Empires: The Age of Discovery",
    "Age of Gods",
    "Age of Industry",
    "Age of Mythology",
    "Age of Steam",
    "Age of Steam Expansion: Time Traveler",
    "Age of War",
    "Aggravation",
    "Agricola",
    "Agricola: Farmers of the Moor",
    "Airships",
    "Akkon: Machtkampf der Tempelritter",
    "Akrotiri",
    "Alba Longa",
    "Alcatraz: The Scapegoat",
    "Alchemist",
    "Alchemists",
    "Alexandros",
    "Alhambra: Big Box",
    "Alhambra: The Card Game",
    "Alien Frontiers",
    "Alien Frontiers: Outer Belt",
    "All Wound Up",
    "Alliances",
    "Amazonas",
    "America's Spirit",
    "Amerigo",
    "Amyitis",
    "Anagramania",
    "Analyze Me",
    "Anasazi",
    "Ancient Terrible Things",
    "Android: Netrunner",
    "Angel Wars Board Game",
    "Angry Birds GO! Memory Game",
    "Anno 1503",
    "Anno 1701: Das Kartenspiel",
    "Antarctica",
    "Antidote",
    "Antike Duellum",
    "Antike II",
    "Antiques Roadshow: The Game",
    "Antler Island",
    "Apocalypse Chaos",
    "Apples to Apples",
    "Apples to Apples to Go",
    "AquaSphere",
    "Aquileia",
    "Arboretum",
    "Arcana",
    "Archipelago",
    "Arctic Survival",
    "Are You Smarter Than a 5th Grader?",
    "Arimaa",
    "Arkham Horror",
    "Arkham Horror: Black Goat of the Woods",
    "Arkham Horror: Innsmouth Horror Expansion",
    "Armada",
    "Army of Frogs",
    "Around the World in 80 Days",
    "Ars Mysteriorum",
    "Artefakt",
    "Artifact",
    "Artus",
    "Asara",
    "Ascending Empires",
    "Ascension: Chronicle of the Godslayer",
    "Ascension: Storm of Souls",
    "Asphodel",
    "Assault on Doomrock",
    "At the Gates of Loyang",
    "Atlanteon",
    "Atlantis",
    "Atlantis Rising",
    "Aton",
    "Attila",
    "Augsburg 1520",
    "Augustus",
    "Augustus",
    "Austin Poker",
    "Avalon Hill Game Company's Game of Trivia",
    "Awkward Family Photos",
    "Axis & Allies",
    "Axis & Allies Pacific 1940",
    "Axis & Allies: 1942",
    "Axis & Allies: D-Day",
    "Axis and Allies 1941",
    "Baba Yaga",
    "Babble",
    "Bacchus",
    "Bacchus' Banquet",
    "Backseat Drawing",
    "Backseat Drawing Jr.",
    "Baffle Gab",
    "Bakong",
    "Balderdash",
    "Baltimore & Ohio",
    "Banana Express",
    "Bananagrams",
    "Bandu",
    "BANG!",
    "Bargain Hunter",
    "Barony",
    "Basari",
    "Baseball Strategy",
    "Basilica",
    "Batt'l Kha'os",
    "Battle Beyond Space",
    "Battle Cry",
    "Battle for Sularia",
    "Battle of the Sexes",
    "BattleLore",
    "BattleLore (Second Edition)",
    "BattleLore: Call to Arms",
    "BattleLore: Dwarven Battalion Specialist Pack",
    "BattleLore: Goblin Marauders Specialist Pack",
    "BattleLore: Goblin Skirmishers Specialist Pack",
    "BattleLore: Scottish Wars",
    "Battleship",
    "Battleship Galaxies: The Saturn Offensive Game Set",
    "Battlestar Galactica",
    "Battlestar Galactica: Exodus Expansion",
    "Battlestar Galactica: Pegasus Expansion",
    "Bausack",
    "Beat the Experts",
    "Bedpans & Broomsticks",
    "Belfort",
    "Betrayal at House on the Hill",
    "Between Two Cities",
    "Beyond the Supernatural",
    "Bezzerwizzer",
    "Big Boggle",
    "Bigfootses, The Card Game",
    "BioShock Infinite: The Siege of Columbia",
    "Bison: Thunder on the Prairie",
    "Black Fleet",
    "Black Friday",
    "Black Sheep",
    "Bling Bling Gemstone",
    "Blockers",
    "Blokus",
    "Blokus Trigon",
    "Blood Bound",
    "Blood Bowl: Team Manager - The Card Game",
    "BloodLust",
    "Blue",
    "Blueprints",
    "Boggle",
    "Bohnanza",
    "Bonanza Rummy",
    "Boomtown",
    "Bootleggers",
    "Booty",
    "Bora Bora",
    "Boss Monster: The Dungeon Building Card Game",
    "Bowling Zombies",
    "Boxcars",
    "Brass",
    "Bremerhaven",
    "Bridgetown Races",
    "Bring Out Yer Dead",
    "Broom Service",
    "Broomsticks and Backflips (aka Hexenhochhaus)",
    "Bruges",
    "Bruges: The City on the Zwin",
    "Buffalo",
    "Buffy the Vampire Slayer: The Game",
    "Burgoo",
    "Burokratopoly",
    "Burrows",
    "Busy Bodies",
    "Buy Low Sell High",
    "Byzantium",
    "Ca$h 'n Gun$: Yakuzas",
    "Cabale",
    "Cacao",
    "Caffeine Rush",
    "Caligula",
    "Callisto",
    "Cambio",
    "Camel Up",
    "Camelot Legends",
    "Campaign Manager 2008",
    "Can't Stop",
    "Canalis",
    "Candamir: The First Settlers",
    "Candy Land",
    "Canterbury",
    "Cape Horn",
    "Cappuccino",
    "Caravans of Ahldarahd",
    "Carcassonne",
    "Carcassonne New World",
    "Carcassonne: Gold Rush",
    "Carcassonne: Hunters and Gatherers",
    "Carcassonne: South Seas",
    "Carcassonne: The Castle",
    "Carcassonne: The Discovery",
    "Cards Against Humanity",
    "Cargo",
    "Cargo Noir",
    "Caribbean",
    "Carpe Astra",
    "Carson City",
    "Cartoona",
    "Casa Grande",
    "Cashflow 101",
    "Casino Bingo",
    "Castellers",
    "Castelli",
    "Castellion",
    "Castle Lords",
    "Castle Panic",
    "Castle Panic: The Wizard's Tower",
    "Castles of Mad King Ludwig",
    "Catacombs",
    "Catan",
    "Catan Histories: Merchants of Europe",
    "Catan Histories: Settlers of America – Trails to Rails",
    "Catan: 5-6 Player Extension",
    "Catan: Cities & Knights",
    "Catan: Cities & Knights; 5-6 Player Extension",
    "Catan: Explorers & Pirates",
    "Catan: Gallery Edition",
    "Catan: Junior",
    "Catan: Kids",
    "Catan: Portable Edition",
    "Catan: Rivals",
    "Catan: Rivals Age of Darkness",
    "Catan: Rivals Age of Enlightenment",
    "Catan: Seafarers",
    "Catan: Seafarers - 5-6 Player Extension",
    "Catan: Star Trek",
    "Catan: Star Trek Federation Space Map Set",
    "Catan: Struggle",
    "Catan: Traders & Barbarians",
    "Catan: Traders & Barbarians: 5-6 Player Extension",
    "Catan: Travel Edition",
    "Catan: Traveler – Compact Edition",
    "Catch the Bingo",
    "Cathedral: Deluxe Edition",
    "Cave Troll",
    "Caveman Curling",
    "Cavemen: The Quest for Fire",
    "Caverna: The Cave Farmers",
    "Cavum",
    "Caylus",
    "Celtica",
    "Champions of Midgard",
    "Change Horses",
    "Chaosmos",
    "Charades for Kids",
    "Charon Inc.",
    "Charoodles",
    "Cheeky Monkey",
    "Chelsea",
    "Chess",
    "Chess for Juniors",
    "Chez Geek",
    "Chez Geek 3: Block Party",
    "Chicago Poker",
    "Chicken Caesar",
    "Chicken Limbo",
    "China",
    "Chinese Revolution",
    "Cineplexity",
    "Cinque Terre",
    "Circular Reasoning",
    "Citadels",
    "Cities",
    "City Council",
    "City Hall",
    "City of Horror",
    "City of Iron",
    "City of Remnants",
    "Claustrophobia",
    "Claustrophobia: De Profundis",
    "Claustrophobia: Furor Sanguinis",
    "Cleopatra and the Society of Architects",
    "Cleopatra's Caboose",
    "Cloud 9",
    "Clue",
    "Clue Jr.: The Case of the Missing Cake",
    "Clue: 1960 Edition",
    "Cluzzle",
    "Co-Mix",
    "Coal Baron",
    "Code 777",
    "Code of Nine",
    "Codenames",
    "Coin Age",
    "Collateral Damage",
    "Colossal Arena",
    "Colosseum",
    "Colt Express",
    "Commander-In-Chief",
    "Compounded",
    "Concept",
    "Concordia",
    "Confucius",
    "Confusion:  Espionage and Deception in the Cold War",
    "Connect 4 (Revised Edition)",
    "Conquest of Pangea",
    "Conquest of Planet Earth: The Space Alien Game",
    "Conquest of the Empire",
    "Conquest of the Fallen Lands",
    "Continental Express",
    "Cootie",
    "Copycat",
    "Coraxis & Co.",
    "Core Worlds",
    "Cornucopia",
    "Cortez",
    "Corto",
    "Cosmic Encounter (Fantasy Flight)",
    "Cosmic Encounter: Cosmic Alliance",
    "Council of Verona",
    "Coup",
    "Coup: Reformation",
    "Courtier",
    "Cover Your Tracks",
    "Cowboys: The Way of the Gun",
    "Cowtown",
    "CO₂",
    "CO₂",
    "Crack the Case",
    "Cranium",
    "Cranium Hoopla",
    "Cranium Scribblish",
    "Cranium Whoonu",
    "Crap or Slap! What Would You Do?",
    "Crappy Birthday",
    "Crash by Crash",
    "Crazy Creatures of Dr. Doom",
    "Crazy Diamond & Karatino",
    "Crazy Office",
    "Cribb Golf",
    "Cribbage",
    "Crocodile Pool Party",
    "CrossWays",
    "Crude: The Oil Game",
    "Cruel Necessity",
    "Cthulhu Rising",
    "Cuba",
    "Cuba: El Presidente",
    "Cube Quest",
    "Cults Across America",
    "Cutthroat Caverns",
    "CV",
    "Cyclades",
    "Cyclades: Titans",
    "Cyrano",
    "D-Day Dice",
    "Darjeeling",
    "Dark Darker Darkest",
    "Dark Gothic",
    "Dark Minions",
    "Dark Moon",
    "Dark Seas",
    "Dark Side",
    "David & Goliath",
    "DaVinci's Mancala",
    "Days of Steam",
    "DC Comics Deck-Building Game",
    "De Vulgari Eloquentia",
    "Dead Drop",
    "Dead Man's Treasure",
    "Dead of Winter: A Crossroads Game",
    "Dead Panic",
    "Deadwood",
    "Deadwood Studios USA",
    "Death Wears White",
    "Defenders of the Realm",
    "DELUXE BACKGAMMON",
    "Deluxe Hanabi",
    "Deluxe Sequence",
    "Democracy: Majority Rules",
    "Der Herr der Ringe: Die Gefährten",
    "Der Herr der Ringe: Die Zwei Türme",
    "Der Weg nach Drakonia",
    "Descent: Journeys in the Dark (Second Edition)",
    "Descent: Journeys in the Dark (Second Edition); Lair of the Wyrm",
    "Destination Tresor",
    "Deus",
    "Diamonds",
    "Diamonsters",
    "Dice City",
    "Dice Run",
    "DICEcapades",
    "Dicecapades! Kerfuffle!",
    "DICEcapades: Pizza Party",
    "Die Kleinen Zauberlehrlinge",
    "Dimension",
    "Dino BOOOM",
    "Dino Mix and Match",
    "Diplomacy",
    "Dirty Minds: The Game of Naughty Clues",
    "Disaster Looms!",
    "Disaster Looms!: CEOs and Corporations",
    "Discount Salmon",
    "Discover India",
    "Discover Omaha",
    "Discoveries",
    "Discworld: Ankh-Morpork",
    "Disorder",
    "Dixit Jinx",
    "Dixit Odyssey",
    "Dixit: Journey",
    "Dizios",
    "Doge",
    "Dominare",
    "Dominion Big Box (English)",
    "Dominion: Intrigue",
    "Dominion: Seaside",
    "Dominoes",
    "Don't Wake Daddy",
    "Doodle Jump",
    "Doom and Bloom SURVIVAL!",
    "Doom: The Boardgame",
    "Doom: The Boardgame Expansion Set",
    "Doomtown: Reloaded",
    "Dos Rios",
    "Double Double Dominoes",
    "Double or Nothing",
    "Double Some'R'Set",
    "Double Take",
    "Dr. Seuss Green Eggs and Ham Game",
    "Dr. Shark",
    "Dragon Caster",
    "Dragon Farkle",
    "Dragon Parade",
    "Dragon Quest",
    "Dragon Strike",
    "Dragon Whisperer",
    "Dragon's Gold",
    "DragonFlame",
    "Dragonheart",
    "Dragonland",
    "Dragonriders",
    "Drakon (third edition)",
    "Dream Factory",
    "Drum Roll",
    "DUDO (Liar's Dice)",
    "Duel in the Dark",
    "Dune",
    "Dungeon Fighter Board Game",
    "Dungeon Lords",
    "Dungeon Lords: Festival Season",
    "Dungeon Petz",
    "Dungeon Roll",
    "Dungeon Run",
    "Dungeon!",
    "DungeonCraft Hero vs. Guardian: A Game of Dungeon Creation",
    "Dungeons & Dragons: Conquest of Nerath Board Game",
    "Dungeons & Dragons: The Legend of Drizzt Board Game",
    "Dungeons & Dragons: Wrath of Ashardalon Board Game",
    "Dungeonville",
    "Duplik",
    "Dust",
    "Dust Tactics",
    "DVONN",
    "Dwarven Dig!",
    "Earth Reborn",
    "Easy Money",
    "Eclipse",
    "Eclipse: Rise of the Ancients",
    "Edo",
    "Eight-Minute Empire",
    "Eight-Minute Empire: Legends",
    "Eketorp",
    "El Caballero",
    "El Capitan",
    "El Grande Decennial Edition",
    "Elder Sign",
    "Electronic Catch Phrase",
    "Electronic Stratego",
    "Elfenland",
    "Elysium",
    "Eminent Domain",
    "Eminent Domain: Escalation",
    "Eminent Domain: Microcosm",
    "Emira",
    "Empire Builder",
    "Empires: The Age of Discovery - Builder Expansion",
    "Enchanted Forest",
    "Endeavor",
    "Enigma",
    "Epic Spell Wars of the Battle Wizards: Duel at Mt. Skullzfyre",
    "Escape: Illusions",
    "Escape: Quest",
    "Escape: The Curse of the Temple",
    "Euphoria: Build a Better Dystopia",
    "Euphrates & Tigris: Contest of Kings",
    "Evolution",
    "Exago",
    "Executive Decision",
    "Exodus: Proxima Centauri",
    "Expédition Altiplano",
    "Expedition: Famous Explorers",
    "Express 01",
    "FAB: Sicily",
    "Fact or Crap",
    "Facts in Five",
    "Fairy Tale",
    "Family Guy Trivia Game",
    "Fangface",
    "Fantasy Frontier",
    "Fauna",
    "Faux•Cabulary",
    "Fealty",
    "Fearsome Floors",
    "Felinia",
    "Feudal",
    "Fibber",
    "Fields of Arle",
    "Finca",
    "Fire & Axe: A Viking Saga",
    "Fireball Island",
    "Firefly: Out to the Black",
    "Firefly: The Game",
    "Firefly: The Game – Breakin' Atmo",
    "First Orchard",
    "First Train to Nuremberg",
    "Fishing for Terrorists Version 2.0",
    "FITS",
    "Five Crowns",
    "Five Fingered Severance",
    "Five Tribes",
    "Five Tribes: The Artisans of Naqala",
    "Flapjacks and Sasquatches",
    "Flash Point: Fire Rescue",
    "Flickin' Chicken",
    "Flinch",
    "Flinke Flitzer (Zippy Cars)",
    "Flip City",
    "Flip For It",
    "Flock",
    "Florenza",
    "Fluxx",
    "Fluxx: The Board Game",
    "Football Strategy",
    "For Sale",
    "For The Win",
    "Forbidden Desert",
    "Forbidden Island",
    "Forbidden Stars",
    "Forever Young: A Vampire Game",
    "Formula D",
    "Fortress America",
    "Fortune and Glory: The Cliffhanger Game",
    "Founding Fathers",
    "Francis Drake",
    "Freedom: The Underground Railroad",
    "Fresco: Big Box",
    "Freya's Folly",
    "Friedrich",
    "Fruit Fair",
    "Fruttirelli",
    "Funemployed!",
    "Funkenschlag: EnBW",
    "Funny Bunny",
    "Funny Business",
    "Fury of Dracula",
    "Fury of Dracula (third edition)",
    "Fuse",
    "Fuzzy Tiger",
    "G.I. Joe Card Game",
    "Galactic Emperor",
    "Galaxy Defenders",
    "Galaxy Defenders: Elite Alien Army",
    "Galaxy Trucker",
    "Galaxy's Edge",
    "Game of Crowns",
    "Gang of Four",
    "Garage Band: The Game",
    "Garden Dice",
    "Gauntlet of Fools",
    "Gears of War: The Board Game",
    "Gearworld: The Borderlands",
    "Geek Out!",
    "Geist",
    "Geist Junior",
    "Genegrafter",
    "Genesis",
    "Genji",
    "Gentlemen Thieves",
    "German Railways",
    "Get Bit!",
    "Gheos",
    "Ghost Stories",
    "GiftTRAP",
    "Ginkgopolis",
    "GIPF",
    "GIPF  Project Set 1",
    "GIPF Project Set 2",
    "GIPF Project Set 3",
    "Gipsy King",
    "Giza: The Great Pyramid",
    "Gladiatori",
    "Glass Road",
    "Glen More",
    "Glenn's Gallery",
    "Global Pursuit",
    "Global Warming",
    "Globalization",
    "Gloom",
    "Gnome Tribes",
    "Go",
    "Go",
    "Go Teddy Go!",
    "Go West",
    "Go-Matria",
    "Goa",
    "Goblins Drool, Fairies Rule!",
    "Goblins, Inc.",
    "Gold Ahoy!",
    "Gold Mine",
    "Goldbräu",
    "Golden Gate",
    "Gonzaga",
    "Good Help",
    "Gouda! Gouda!",
    "Gracias",
    "Graenaland",
    "Granada",
    "Grand Austria Hotel",
    "Grand Conquest",
    "Grave Business",
    "Gravediggers",
    "Gravwell: Escape from the 9th Dimension",
    "Greed Quest",
    "Grog Island",
    "Ground Floor",
    "Guess Who?",
    "Guesstures",
    "Guildhall",
    "Guildhall: Job Faire",
    "Guillotine",
    "Gunship: First Strike!",
    "Ha! Ha! Moustache",
    "Hacienda",
    "Haleakala",
    "Halloween Party",
    "Halo Interactive Strategy Game",
    "Hanabi",
    "Hanging Gardens",
    "Hannibal: Rome vs. Carthage",
    "Hansa",
    "Hansa Teutonica",
    "Hansa Teutonica: East Expansion",
    "Hare & Tortoise",
    "Harry Potter and the Sorcerer's Stone Trivia Game",
    "Hawaii",
    "Healing Blade: Infectious Disease Card Battle",
    "Hear Me Out",
    "Hedbanz for Kids",
    "Hedbanz: For Adults",
    "Hegemonic",
    "Helios",
    "HellRail: Third Perdition",
    "Helvetia Cup",
    "Hengist",
    "HeroCard Galaxy",
    "HeroCard Nightmare",
    "HeroCard Rise of the Shogun",
    "Heroes of Metro City",
    "Heroes Of The World",
    "Hexenkompott",
    "Hey, That's My Fish!",
    "Hi Ho! Cherry-O",
    "Hidden Conflict",
    "Hide the Kids!",
    "High Frontier",
    "High Frontier Expansion",
    "High Noon Saloon",
    "Hirelings the Ascent",
    "Hispaniola",
    "Hive",
    "Homesteaders",
    "Hoot Owl Hoot!",
    "Hooyah: Navy Seals Card Game",
    "Horse Fever",
    "Horse Show",
    "Horus Heresy",
    "Hospital Rush",
    "Hot Rod Creeps",
    "Hot Spot",
    "Hot Spot",
    "Hot Tin Roof",
    "Hotel Samoa",
    "Hotel Tycoon",
    "Hungry Hungry Hippos",
    "Hunting Party",
    "Hurry'Cup!",
    "Husker Hysteria",
    "Hyperborea",
    "I Am Vlad: Prince of Wallachia",
    "Ice Cream",
    "Ice Lake",
    "Ideology: The War of Ideas",
    "Ido",
    "Igels: Das Kartenspiel",
    "Ikusa",
    "Il Principe",
    "Il Vecchio",
    "Illusio",
    "Imaginiff",
    "Imperial",
    "Imperial Settlers",
    "In Limbo",
    "In the City: Origins",
    "In the Shadow of the Emperor",
    "In the Year of the Dragon",
    "Incan Gold",
    "Indigo",
    "Indus",
    "Industry",
    "Infamy",
    "Infiltration",
    "Infinite City",
    "Infunitum",
    "Ingenious",
    "Inkognito",
    "Innsmouth Escape",
    "Invasion from Outer Space: The Martian Game",
    "Ion: A Compound Building Game",
    "Iron Chef Board Game: The Ultimate Cooking Challenge",
    "Isla Dorada",
    "Isle of Skye: From Chieftain to King",
    "Istanbul",
    "It Happens..",
    "It's Alive!",
    "Itinerary",
    "Jamaica",
    "Jambo",
    "Jantaris",
    "Jeff Foxworthy's You Might Be a Redneck if... Game",
    "Jenga Max",
    "Jenga Vintage Wood Book Edition",
    "Jenga Xtreme",
    "Jitters",
    "Johari",
    "Journey to the Center of the Earth",
    "Jungle Speed",
    "Junkyard Races",
    "Junta",
    "Kairo",
    "Kalua",
    "Kamisado",
    "Kanban: Automotive Revolution",
    "Karesansui",
    "Katamino",
    "Katamino Duo",
    "Keltis",
    "Kemet",
    "Key Harvest",
    "Keyflower",
    "Khet: The Laser Game",
    "Kill Doctor Lucky",
    "Killer Bunnies and the Quest for the Magic Carrot",
    "Kimaloé",
    "King Chocolate",
    "King of New York",
    "King of the Beasts: Mythological Edition",
    "King of Tokyo",
    "King Up!",
    "King's Gate",
    "King's Progress",
    "Kingdom Builder",
    "Kingdom of Solomon",
    "Kingdoms",
    "Kings of Air and Steam",
    "Kingsburg",
    "Kingsport Festival",
    "Kittens in a Blender",
    "KLASK",
    "Knight Moves",
    "Knight's Domain",
    "Know It or Blow It",
    "Kobayakawa",
    "Konexi",
    "Konito?",
    "Korrigans",
    "Krysis",
    "La Boca",
    "La Città",
    "La Granja",
    "La Isla",
    "La Loire",
    "La Strada",
    "Ladies & Gentlemen",
    "Lancaster",
    "Lanterns: The Harvest Festival",
    "Las Vegas",
    "Lascaux",
    "Last Man Standing",
    "Last Mouse Lost",
    "Last Night on Earth: Blood in the Forest",
    "Last Night on Earth: Blood in the Forest",
    "Last Night on Earth: The Zombie Game",
    "Last Night on Earth: Timber Peak",
    "Last Will",
    "Launch Pad",
    "Le Havre",
    "League of Six",
    "Leaping Lizards",
    "Legacy: Gears of Time",
    "Legacy: The Testament of Duke de Crecy",
    "Legendary: A Marvel Deck Building Game",
    "Legends of Andor",
    "Legitimacy",
    "Lemonade Stand",
    "LetterFlip",
    "Letters from Whitechapel",
    "Level 7 [Escape]",
    "Lewis & Clark",
    "Libertalia",
    "Liberté",
    "LineUp",
    "Linja",
    "Linkage: A DNA Card Game",
    "Linkee",
    "Linq",
    "Little Italy",
    "Livingstone",
    "Loch Ness",
    "Log Jam",
    "Logan Stones",
    "Logo Party",
    "LOKA: A Game of Elemental Strategy",
    "London",
    "Long Shot",
    "Lord of the Rings",
    "Lord of the Rings: The Duel",
    "Lords of Vegas",
    "Lords of Vegas: UP!",
    "Lords of Waterdeep",
    "Lords of Waterdeep: Scoundrels of Skullport",
    "Lords of Xidit",
    "Lords of Xidit: Bonus Titans Promo",
    "Lost Cities",
    "Lost Cities: The Board Game",
    "Lost Legacy: Flying Garden",
    "Lost Legacy: Second Chronicle – Vorpal Sword & Whitegold Spire",
    "Lost Legacy: The Starship",
    "Lost Legacy: Third Chronicle – Sacred Grail & Staff of Dragons",
    "Lost Legends",
    "Lost Legends: Forest of the Damned (Queenie 2)",
    "Lost Temple",
    "Lost Valley: The Yukon Goldrush 1896",
    "Lost: The Game",
    "Love Letter",
    "Love Letter: The Hobbit – The Battle of the Five Armies",
    "Luna",
    "Lungarno",
    "Lupin the 3rd",
    "Lyssan",
    "Maask",
    "Macao",
    "Machi Koro",
    "Machi Koro: Harbor Expansion",
    "Machine of Death: The Game of Creative Assassination",
    "Mad Gab",
    "Madame Ching",
    "Madeira",
    "Mafia de Cuba",
    "Magdar",
    "Mage Knight Board Game",
    "Magical Athlete",
    "Magician's Kitchen",
    "Magnet",
    "Magnetic Fishing",
    "Maharani",
    "Make 'n' Break",
    "Malarky",
    "Mall of Horror",
    "Mall World",
    "Malta!",
    "Mammut",
    "Mancala",
    "Manga Manga",
    "Mansions of Madness",
    "Mansions of Madness: Call of the Wild",
    "Mansions of Madness: Forbidden Alchemy",
    "Maori",
    "Mapominoes: Europe",
    "Marbles",
    "Marrying Mr. Darcy",
    "Martian Dice",
    "Mascarade",
    "Master Builder",
    "Master Fox",
    "Mastermind for Kids",
    "Masters Gallery",
    "Masters of Venice",
    "Matchstix",
    "Mecanisburg",
    "Medici",
    "Medieval Academy",
    "Medina (second edition)",
    "MegaCorps",
    "Meltdown 2020",
    "Memoir '44",
    "Memory",
    "Mentalogy",
    "Mercante",
    "Merchant of Venus",
    "Merchants & Marauders",
    "Merchants of Amsterdam",
    "Merchants of the Middle Ages",
    "Merkator",
    "Mermaid Rain",
    "Metal Adventures",
    "Metro",
    "Metropolys",
    "Mexica",
    "Mice and Mystics",
    "Mice and Mystics: Heart of Glorm",
    "Micro Monsters",
    "Micro Monsters",
    "Middle Kingdom",
    "Mille Bornes",
    "MindTrap",
    "Ming Dynasty",
    "Mirror, Mirror",
    "Miskatonic School for Girls",
    "Mission: Red Planet",
    "Moai",
    "Moby Dick, or, The Card Game",
    "Modern Art",
    "Modern Society",
    "Mogul",
    "Mondo",
    "Money!",
    "Monkey Lab",
    "Monkeys on the Moon",
    "Monolith: The Strategy Game",
    "Monopoly",
    "Monopoly Deal Card Game",
    "Monopoly: Millennium",
    "Monopoly: Star Wars",
    "Monster auf der Flucht",
    "Monster Factory",
    "Monster Town",
    "Monsters Menace America",
    "Monty Python Fluxx",
    "Monuments: Wonders of Antiquity",
    "Morphology",
    "Mother Sheep",
    "Mouse Trap",
    "Mousquetaires du Roy",
    "Moustache Smash",
    "Mr. Jack",
    "Mr. Jack Extension",
    "Mr. Jack in New York",
    "Mr. Jack Pocket",
    "Munchkin 4: The Need for Steed",
    "Munchkin 5: De-Ranged",
    "Munchkin Axe Cop",
    "Munchkin Cthulhu",
    "Munchkin Deluxe",
    "Munchkin Dice",
    "Munchkin Impossible",
    "Munchkin Quest",
    "Munchkin Quest 2: Looking for Trouble",
    "Munchkin Zombies",
    "Murano",
    "Murder City",
    "Murder Makes a Call",
    "Musketeers",
    "My Precious Presents",
    "Myrmes",
    "Mysterium",
    "Mystery Express",
    "Mystery of the Abbey with The Pilgrims' Chronicles",
    "Mystery! Motive for Murder",
    "Mythic Battles",
    "Mythic Battles: Expansion 1 - Heroes Bloody Dawn",
    "Nab-It!",
    "Nacht der Magier",
    "Nations",
    "Nautilus",
    "Navegador",
    "Neanderthal",
    "Nefertiti",
    "Neuland",
    "Neuroshima Hex!",
    "Neuroshima Hex! Babel 13",
    "Neuroshima Hex! Duel",
    "New Amsterdam",
    "New Scotland Yard: Crime Scene",
    "New York",
    "New York 1901",
    "Nexus Ops",
    "Niagara",
    "Nichtlustig Doppelgänger",
    "Night of the Grand Octopus",
    "Ninja Burger",
    "Ninja Galaxy",
    "Ninja Versus Ninja",
    "Ninja: Legend of the Scorpion Clan",
    "Ninjato",
    "Niya",
    "No Peeking!",
    "No Thanks!",
    "Noblemen",
    "Nomads of Arabia: The Wandering Herds Game",
    "North Wind",
    "Nothing Personal",
    "Nothing Personal: Young Turks Expansion",
    "Number Ninjas",
    "Nuns on the Run",
    "Oasis",
    "Obstgarten: Das Memospiel",
    "Odd Jobs",
    "Odin's Ravens",
    "Oltre Mare",
    "Olympos",
    "Olympus",
    "Omaha On Board",
    "On the Underground",
    "One Night Revolution",
    "One Night Ultimate Vampire",
    "One Night Ultimate Werewolf",
    "One Night Ultimate Werewolf Daybreak",
    "Oodles",
    "Oodles",
    "Oodles of Doodles",
    "Ooga!",
    "Open Season",
    "Operation",
    "Operation: Maccabee",
    "Orchard",
    "Orcs Orcs Orcs",
    "Order of the Stick Adventure Game: The Dungeon of Dorukan",
    "Order's Up!",
    "Oregon",
    "Origin",
    "Original I.Q. Tester",
    "Orphan Black: The Card Game",
    "Ortus",
    "Osmanli Harbi The Ottoman Fronts: 1914 to 1918",
    "Ostia - The Harbor of Rome",
    "Othello",
    "Outburst II",
    "Outburst Junior",
    "Outburst!",
    "Outdoor Survival",
    "Outwit",
    "Overthrone",
    "Owner's Choice",
    "P.I.",
    "Pack and Stack",
    "Pagoda",
    "Palenque",
    "Pamplona: Viva San Fermín!",
    "Panamax",
    "Pandemic",
    "Pandemic: Contagion",
    "Pandemic: In the Lab",
    "Pandemic: On the Brink",
    "Pandemic: State of Emergency",
    "Pandemic: The Cure",
    "Panic Station",
    "Pantheon",
    "Pants on Fire!",
    "Panzer General: Russian Assault",
    "Panzer Leader",
    "Parade",
    "Paradise Fallen: The Card Game",
    "Parcheesi",
    "Parcheesi: Gold Seal Edition",
    "Parfum",
    "Paris Connection",
    "Pass the Pigs",
    "Passing The Bar",
    "Patchwork",
    "Patrician",
    "PBL Robots",
    "Pengoloo",
    "Penguin",
    "Penny Press",
    "Pentago",
    "Pente",
    "Peptide: A Protein Building Game",
    "Pergamon",
    "Perpetual Commotion",
    "Picknick Panik",
    "Pickomino",
    "Pictionary",
    "Pictomania",
    "Pictureseeker's game: Art Memory",
    "Piña Pirata",
    "Pirate Dice: Voyage on the Rolling Seas",
    "Pirate's Cove",
    "Piraten, Planken & Peseten",
    "Pirates 2ed: Governor's Daughter",
    "Pirates on the High Seas",
    "Piratissimo",
    "Pizza Theory",
    "Planes",
    "Planet Steam",
    "Playing Cards",
    "Point Of Law",
    "Pokemon Memory Game",
    "Polygon",
    "Ponte del Diavolo",
    "Pony Express",
    "Porta Nigra",
    "Portal: The Uncooperative Cake Acquisition Game",
    "Porto Carthago",
    "Portobello Market",
    "Poseidon",
    "Power Grid",
    "Power Grid deluxe: Europe/North America",
    "Power Grid: Benelux/Central Europe",
    "Power Grid: Brazil/Spain & Portugal",
    "Power Grid: China/Korea",
    "Power Grid: Factory Manager",
    "Power Grid: France/Italy",
    "Power Grid: Northern Europe / United Kingdom & Ireland Expansion",
    "Power Grid: Québec/Baden-Württemberg",
    "Power Grid: Russia & Japan",
    "Power Grid: The First Sparks",
    "Power Grid: The Robots",
    "Power Lunch",
    "Pressure Cooker",
    "Pressure Point",
    "Prestige",
    "Priests of Ra",
    "Princes of the Dragon Throne",
    "Principato",
    "Prolix",
    "Prosperity",
    "Puerto Rico",
    "PÜNCT",
    "Pyramidion",
    "Qin",
    "Quadtria",
    "Quantum",
    "Quanzy",
    "Quarantine",
    "Québec",
    "Queen of the Cupcakes",
    "Queen's Necklace",
    "Quelf",
    "Quilt Show",
    "Quo Vadis?",
    "Quoridor",
    "Qwirkle",
    "Qwirkle Berkshire Hathaway",
    "Qwirkle Trio",
    "Qwixx",
    "Ra",
    "Ra: Uberplay Edition",
    "Rabbit Hunt",
    "Race for the Galaxy",
    "Race for the Galaxy: Alien Artifacts",
    "Raceway 57",
    "Railroad Barons",
    "Railways of the World",
    "Railways of the World: The Card Game",
    "Railways Through Time",
    "Rainbows",
    "Rampage",
    "Ranking",
    "Raptor",
    "Rasputin",
    "Rattle, Battle, Grab the Loot",
    "Rattlebones",
    "RATTLESNAKE",
    "Red November",
    "Reef Encounter",
    "Reef Encounter of the Second Kind",
    "ReFraze",
    "Régents",
    "Relic Runners",
    "Reverse Charades",
    "Reverse Charades Junior Edition",
    "Revolution!",
    "Revolution! The Palace",
    "Revolver",
    "Rex: Final Days of an Empire",
    "Rialto",
    "Ricochet Robots",
    "Ricochet Rock Jockeys",
    "Riddles & Riches",
    "Ringgz",
    "Rio de la Plata",
    "Rise of the Zombies! the Zombie Apocalypse Survival Board Game",
    "Rise!",
    "Risk",
    "Risk 2210 A.D.",
    "RISK: Mass Effect Galaxy at War Edition",
    "Risk: Star Wars – The Clone Wars Edition",
    "Ristorante Italia",
    "River Dragons",
    "Road Kill Rally",
    "Robber Knights",
    "Robbin' Eggs",
    "RoboRally",
    "Robot Turtles",
    "Rocket Jockey",
    "Rokoko (aka Rococo)",
    "Roll For It!",
    "Roll For It! (Purple)",
    "Roll for the Galaxy",
    "Roll to the South Pole",
    "Roller Coaster Tycoon",
    "ROLLICK!  The Hysterical Game of Clues and Collaboration",
    "Romance of the Nine Empires",
    "Rook",
    "Room 25",
    "Rules of the Game",
    "Rumis",
    "Rummikub",
    "Runebound (Second Edition)",
    "Runewars",
    "Runewars: Banners of War",
    "Ruse",
    "Russian Railroads",
    "Russian Rails",
    "Saboteur",
    "Saboteur 2 (expansion-only editions)",
    "Saint Malo",
    "Saint Petersburg (second edition)",
    "Salem",
    "Salmon Run",
    "Samurai",
    "Samurai",
    "Samurai Spirit",
    "Samurai Sword",
    "Santiago",
    "Santiago de Cuba",
    "Sapiens",
    "Saqqara",
    "Savannah Tails",
    "Save Doctor Lucky",
    "Say Anything",
    "Say Anything Family Edition",
    "Scandaroon",
    "Scarab Lords",
    "Scattergories",
    "Scotland Yard",
    "Scrabble",
    "Scrabble Sentence Cube Game",
    "Scrabble Slam!",
    "Scrappers",
    "Scripts and Scribes: The Dice Game",
    "Seasons",
    "Secrets of the Tombs",
    "Sedition Wars: Battle for Alabaster",
    "Seize the Day!",
    "Sentence Cube Game",
    "Serenissima",
    "Set Dice",
    "Settlers of America: Trails to Rails",
    "Seven Dragons",
    "Sewer Pirats",
    "Shadow Hunters",
    "Shadows of Brimstone: City of the Ancients",
    "Shadows of Brimstone: Swamps of Death",
    "Shadows of Malice",
    "Shadows over Camelot",
    "Shafausa",
    "Shakespeare",
    "Shakespeare: The Bard Game",
    "Shanghaien",
    "Shear Panic",
    "Sheriff of Nottingham",
    "Sherlock Deluxe",
    "Sherlock Holmes Consulting Detective",
    "Sherwood Forest",
    "Shinobi WAT-AAH!",
    "Shipwrecked",
    "Shipyard",
    "Shogun",
    "Shogun: Tenno's Court",
    "Shootin' Ladders: Frag Fest",
    "Show Manager",
    "Siam",
    "Sid Meier's Civilization: The Board Game",
    "Sidibaba",
    "Siena",
    "Silk Road",
    "Silverton",
    "Simply Catan",
    "Six-Word Memoirs",
    "Skip-Bo MOD",
    "Sky Tango",
    "Sky Traders",
    "Skyline",
    "Skyline 3000",
    "Skyskraper",
    "Slap Jack",
    "Small World",
    "Small World Underground",
    "Smart Ass",
    "Smart Cookies",
    "Smash Up",
    "Smash Up: Monster Smash",
    "Smugglers: A Family Friendly Strategy Game",
    "Snail's Pace Race",
    "Snake Oil",
    "Sneeze",
    "Snowdonia",
    "Snowdonia: Jungfraubahn & Mount Washington",
    "Sobek",
    "Soli2",
    "Solitaire For Two",
    "Something Different",
    "Sorry!",
    "Space Cadets",
    "Space Cadets: Resistance Is Mostly Futile",
    "Space Checkers",
    "Space Dealer",
    "Space Empires: 4X",
    "Space Junkyard",
    "Space Mission",
    "Space Pigs",
    "Space Pirates",
    "Space Sheep!",
    "Space Shuffle",
    "Spammers",
    "Sparta",
    "Specter Ops",
    "Spectral Rails",
    "Spellcaster",
    "Spiel",
    "Spike",
    "Spin Monkeys",
    "Spirits of the Rice Paddy",
    "Splendor",
    "Splendor",
    "Sports Illustrated Baseball/Pennant Race",
    "Spotcha!",
    "Sputnik",
    "Spyfall",
    "Spyrium",
    "Squadron Scramble",
    "Squiggle",
    "Squint",
    "Star Fluxx",
    "Star Realms",
    "Star Trek Deck Building Game: The Next Generation",
    "Star Trek Expeditions",
    "Star Trek Trivia Game",
    "Star Trek: Five-Year Mission",
    "Star Trek: The Game",
    "Star Trek: The Next Generation: Interactive VCR Board Game: A Klingon Challenge",
    "StarCraft: The Board Game",
    "Starship Catan",
    "Starship Troopers",
    "Starwords",
    "Statis Pro Basketball",
    "Steam",
    "Steam Time",
    "Sticky Fingers",
    "Stocks & Bonds",
    "Stomple",
    "Stone Age",
    "Stone Age: The Expansion",
    "Stop the Presses!",
    "Stowaway 52",
    "Stranded",
    "Stratego",
    "Strato Chess",
    "Street Illegal",
    "Strike Dice",
    "Strike of the Eagle",
    "String Safari",
    "Stronghold",
    "Subdivision",
    "Sudoku Deluxe",
    "Sultaniya",
    "Summonaria",
    "Sun Tzu",
    "Super Ker Plunk!",
    "Super Munchkin",
    "Super Munchkin 2: The Narrow S Cape",
    "Super Scrabble",
    "Super Tooth",
    "Surf's Up, Dude!",
    "Surprise!",
    "Survive: Escape from Atlantis!",
    "Survive: Escape from Atlantis! 5-6 Player Mini Expansion",
    "Survive: Escape from Atlantis! The Giant Squid Mini Expansion",
    "Survive: Space Attack!",
    "Sushi Draft",
    "Sushi Go!",
    "Suspend",
    "Sutter's Mill",
    "Sword & Skull",
    "Sylla",
    "Sylvion",
    "Tabletop Pool",
    "Taboo",
    "Taboo for KIDS",
    "Tadaaam!",
    "Tahiti",
    "Tàin",
    "Taj Mahal",
    "Take it Easy!",
    "Take Stock",
    "Takeaway",
    "Takenoko",
    "Takenoko: Chibis",
    "Talat",
    "Tales & Games: The Grasshopper & the Ant",
    "Tales & Games: The Hare and the Tortoise",
    "Tales & Games: The Three Little Pigs",
    "Tales of Ulysse",
    "Tally Ho!",
    "Taluva",
    "Tammany Hall",
    "Targi",
    "Tash-Kalar: Arena of Legends",
    "Tattletale Card Game",
    "Taxi",
    "Tech Bubble",
    "TEE-RIVIA",
    "Telestrations",
    "Tell Tale: Fairy Tales",
    "Templar: The Secret Treasures",
    "Temple Run: Danger Chase",
    "Temporum",
    "Tempus",
    "Teneriffa",
    "Terra",
    "Terra Mystica",
    "Terra Mystica: Fire & Ice",
    "Tesserae",
    "The 3 Commandments",
    "The aMAZEing Labyrinth",
    "The Amazing Mammoth Hunt",
    "The Amberden Affair",
    "The Apprentice",
    "The Ares Project",
    "The Battle at Kemble's Cascade",
    "The Big Book of Madness",
    "The Birthday Game",
    "The Bloody Inn",
    "The Bridges of Shangri-La",
    "The Builders: Middle Ages",
    "The Castles of Burgundy",
    "The Chain Game",
    "The Club",
    "The Doge Ship",
    "The Doom That Came To Atlantic City",
    "The Downfall of Pompeii",
    "The Duke",
    "The Duke: Arthurian Legends Expansion Pack",
    "The Duke: Customization Expansion Pack",
    "The Duke: Musketeers Expansion",
    "The Duke: Robert E. Howard Expansion",
    "The Dutch Golden Age",
    "The End of the Triumvirate",
    "The Farming Game",
    "The Forgotten Planet",
    "The Game of Life",
    "The Game: Spiel... so lange du kannst! (Game... as long as you can!)",
    "The Gnomes of Zavandor",
    "The Golden Ages",
    "The Golden City",
    "The Good Ship Freedom",
    "The Grand Alchemist",
    "The Grape Escape",
    "The Great Fire of London 1666",
    "The Great Heartland Hauling Co.",
    "The Great Persuader",
    "The Grizzled",
    "The Heavens of Olympus",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: An Unexpected Journey – Journey to the Lonely Mountain Strategy Game",
    "The Isle of Doctor Necreaux",
    "The Last Banquet",
    "The Little Prince: Rising to the Stars",
    "The Logo Board Game",
    "The Looney Bin",
    "The Lord of the Rings: The Fellowship of the Ring Deck-Building Game",
    "The Lost Dutchman",
    "The Magic Labyrinth",
    "The Manhattan Project",
    "The Manhattan Project: Nations Expansion",
    "The Market of Alturien",
    "The Mines of Zavandor",
    "The Muppet Show Game",
    "The Mystery of the Templars",
    "The New Science",
    "The Omega Virus",
    "The Origin of Expressions",
    "The Perfect 10",
    "The Perfect Heist",
    "The Phantom Society",
    "The Pillars of the Earth: Builders Duel",
    "The Price Is Right Game DVD",
    "The Prince: The Struggle of House Borgia",
    "The Princes of Florence",
    "The Princess Bride: Storming the Castle",
    "The Red Dragon Inn",
    "The Red Dragon Inn: Allies – Pooky",
    "The Red Dragon Inn: Gambling? I'm In!",
    "The Resistance",
    "The Resistance: Avalon",
    "The Road to Canterbury",
    "The Scrambled States of America",
    "The Secret of Monte Cristo",
    "The Secrets Game",
    "The Settlers of the Stone Age",
    "The Simpsons: Clue",
    "The Speicherstadt",
    "The Stars Are Right",
    "The Staufer Dynasty",
    "The Swarm",
    "The Thief of Baghdad",
    "The Twilight Saga: New Moon – The Movie Board Game",
    "The Very Quiet Cricket Game",
    "The Village Crone",
    "The Voyages of Marco Polo",
    "The Walking Dead Board Game",
    "The Walking Dead: The Board Game",
    "The Whispering Road",
    "The Witcher Adventure Game",
    "The Witches: A Discworld Game",
    "The Wonderful World of Disney Trivia Game",
    "The Worst-Case Scenario Survival Game",
    "Thebes",
    "Theseus: The Dark Orbit",
    "Thingamajig",
    "Things...",
    "Through the Ages: A Story of Civilization",
    "Through the Desert",
    "Thunderbirds",
    "Thurn and Taxis",
    "Thurn and Taxis: All Roads Lead to Rome",
    "Thurn and Taxis: Power and Glory",
    "Tic-Tac-Ku",
    "Tic-Tac-Ku",
    "Ticket to Ride",
    "Ticket to Ride Map Collection: Volume 1 – Team Asia & Legendary Asia",
    "Ticket to Ride Map Collection: Volume 2 – India & Switzerland",
    "Ticket to Ride Map Collection: Volume 3 – The Heart of Africa",
    "Ticket to Ride Map Collection: Volume 4 – Nederland",
    "Ticket to Ride Map Collection: Volume 5 – United Kingdom & Pennsylvania",
    "Ticket to Ride: Alvin & Dexter",
    "Ticket to Ride: Europe",
    "Ticket to Ride: Märklin",
    "Ticket to Ride: Nordic Countries",
    "Ticket to Ride: Switzerland",
    "Ticket to Ride: The Card Game",
    "Ticket to Ride: The Dice Expansion",
    "Tides of Time",
    "Tierra  y Libertad: The Mexican Revolution Game",
    "Tigris & Euphrates",
    "Tikal",
    "Tikal II: The Lost Temple",
    "Tiki Topple",
    "Tilez!",
    "Timbuktu",
    "Timeline Challenge",
    "Timestreams: Medieval vs Modern Day Game",
    "Timestreams: Stone Age vs. Future Tech",
    "Tiny Epic Kingdoms",
    "Tip the Scale",
    "Titanium Wars",
    "Tobago",
    "Toc Toc Woodman",
    "Tokaido",
    "Toledo",
    "Tombouctou",
    "Top Race",
    "Toppo",
    "Torpedo Run!",
    "Torres",
    "Tower of Babel",
    "TPOC: The Politics of Cannibals",
    "Traders of Osaka",
    "Trading Spaces Game",
    "Traditional Card Games",
    "Tragedy Looper",
    "Tragedy Looper: Midnight Circle",
    "Train of Thought",
    "Trains",
    "Trains and Stations",
    "Trains: Rising Sun",
    "Trambahn",
    "Travel Blog",
    "Treasure Hunt",
    "Treasure Quest",
    "Trias",
    "Triassic Terror",
    "Trinidad",
    "Tripoley",
    "Trivia - Omaha",
    "Trivial Pursuit",
    "Trivial Pursuit",
    "Trivial Pursuit: Baby Boomer Edition",
    "Trivial Pursuit: Master Edition",
    "Trivial Pursuit: Millennium Edition",
    "Trivial Pursuit: Sports Edition",
    "Trivial Pursuit: Star Wars Classic Trilogy Collector's Edition",
    "Trivial Pursuit: The Lord of the Rings Movie Trilogy Collector's Edition",
    "Trouble Board Game",
    "Trouble: Despicable Me Edition",
    "Troy Extra Muros",
    "True Colors",
    "True or False",
    "Tsuro",
    "Tsuro of the Seas",
    "Tuchulcha",
    "Tumult Royale",
    "Twilight Imperium (Third Edition): Shattered Empire",
    "Twilight Imperium 3rd Edition",
    "Twilight Imperium: Shards Of The Throne Expansion",
    "Twilight Struggle",
    "Twister",
    "Twixt",
    "Two by Two",
    "Tyrus",
    "TZAAR",
    "Tzolk'in - the Mayan Calendar",
    "Tzolk'in: The Mayan Calendar – Tribes & Prophecies",
    "Ubi",
    "Ubongo",
    "Ubongo Extreme",
    "Ubongo: Duel",
    "Uchronia",
    "Ugg-Tect",
    "Ultimate Stratego",
    "Ultimate Werewolf: Ultimate Edition",
    "Uncharted: The Board Game",
    "Undermining",
    "Unexpected Treasures",
    "Unexploded Cow",
    "Unita",
    "United States of America Picture Map Puzzle",
    "UNO",
    "UNO MOD",
    "Unspeakable Words",
    "Upon a Salty Ocean",
    "Uptown",
    "Upturn",
    "Upwords",
    "UR",
    "Urban Sprawl",
    "Urbania",
    "Urbanization",
    "Utopia",
    "Valley of the Pharaohs - Bookshelf Edition",
    "Vampire Empire",
    "Van Helsing",
    "Vege Tables",
    "Ventura",
    "Venture Forth",
    "Verona",
    "Via Appia",
    "Viceroy",
    "Vikings",
    "Village",
    "Vineta",
    "Visual Brain Storms",
    "Viticulture",
    "VivaJava: The Coffee Game",
    "Vudù",
    "Walhalla",
    "Wallamoppi",
    "Wallenstein",
    "Walnut Grove",
    "War",
    "War and Peace",
    "Warcraft the Board Game",
    "WarCraft: The Board Game Expansion Set",
    "Warehouse 51",
    "Warhamster Rally",
    "Warriors",
    "Warriors: Dragon Hordes Expansion",
    "Wartiles",
    "Waterworks",
    "Way Out West",
    "Web of Gold",
    "Welcome to the Dungeon",
    "Western Town",
    "Whad'Ya Know?",
    "What The Face?",
    "What's in Ned's Head?",
    "What's It To Ya?",
    "What's It?",
    "What?",
    "Whatzit?",
    "Wheeler Dealer",
    "Where in the World?",
    "Who Wants to Be a Millionaire",
    "Wicked Witches Way",
    "Winter Tales",
    "WIT'S END Board Game",
    "Witness",
    "Wits & Wagers",
    "Wits & Wagers Family",
    "Wiz-War (eighth edition)",
    "Wizard's Brew",
    "Wizard's Gambit",
    "Wizard's Quest",
    "Wooly Bully",
    "Word on the Street",
    "Word on the Street Junior",
    "WordSpot - Bookshelf Edition",
    "World of Tanks: Rush",
    "World of Warcraft: The Boardgame",
    "World of Warcraft: The Boardgame - Shadow of War",
    "World War Z: The Game",
    "World Without End",
    "Would You Rather...?",
    "Would You Rather...?",
    "Wrong Chemistry",
    "Wypas",
    "XCOM: The Board Game",
    "XenoShyft Onslaught",
    "Yahtzee",
    "Yam Master",
    "Yamodo Party Time",
    "Yedo",
    "Yggdrasil",
    "YINSH",
    "Yomi",
    "Ys",
    "Yspahan",
    "Zen Garden",
    "ZERTZ",
    "Zeus on the Loose",
    "Zobmondo!! Would You Rather...? Pocket Version",
    "Zombicide",
    "Zombie 15'",
    "Zombie Run!",
    "ZombieTown",
    "Zoneplex",
    "Zong Shi",
    "Zoodiak",
    "Zooloretto",
    "Yedo",
    "Yggdrasil",
    "YINSH",
    "Yomi",
    "Ys",
    "Yspahan",
    "Zen Garden",
    "ZERTZ",
    "Zeus on the Loose",
    "Zobmondo!! Would You Rather...? Pocket Version",
    "Zombicide",
    "Zombie 15'",
    "Zombie Run!",
    "ZombieTown",
    "Zoneplex",
    "Zong Shi",
    "Zoodiak",
    "Zooloretto"
  ]

  x.each do |title|
    fetch_game_info(title)
  end
end